### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ArisneR3** [331leo/Genshin-Daily-Checkin#2]
Did everything as said in 'readme' but it's not working. Shouldn't there be one more step? I remember from other 'daily checkin bot' you had to do something else to make it active.

**Comment by 331leo** [comment]
It works for me well,,
What server are you in?
It doesn't work in China servers.

**Comment by GrabsOrion** [comment]
@331leo, thanks for the repo! 
Can you please add few tips in readme how to set up workflow in Actions for the script?

**Comment by GrabsOrion** [comment]
@ArisneR3, oh, I see now, you need to go to Actions and then select HoYoLAB Attendance workflow and then run it.
I'll check it on Europe server and let you now about results.

**Comment by 331leo** [comment]
> @331leo, thanks for the repo! 
> 
> Can you please add few tips in readme how to set up workflow in Actions for the script?

It already contains Github Actions workflow file.

When someone fork this repo, they will get workflow file included.

I set up cronjob on workflow, and it will run automatically everyday, 7AM UTC

**Comment by ArisneR3** [comment]
> It works for me well,, What server are you in? It doesn't work in China servers.

Europe, and what @GrabsOrion said, that was it. In Actions it says workflows are disabled for forked repos and I had to enable them myself.
